### ISSUE TITLE
error with smcounter2

### ISSUE THREAD

**Issue by lijuanzhang218** [qiaseq/smcounter-v2-paper#3]
Hi,
I'm trying to use smcounter2 to detect SNV on my UMI-based data. But I got a error like this when I use M0253.bam to test.
********************
started at 2020-01-15 17:24:49.944421
('repBed', '/apps/user/zhanglijuan/software/smcounter2/share/smcounter2-0.1.2018.08.28-0/data/annotation/hg19/simpleRepeat.full.bed')
('bamFile', '/apps/user/zhanglijuan/618G/UMI/smcounter2/M0253.bam')
('rpb', 5.0)
('mismatchThr', 6.0)
('hpLen', 8)
('inputVCF', 'none')
('srBed', '/apps/user/zhanglijuan/software/smcounter2/share/smcounter2-0.1.2018.08.28-0/data/annotation/hg19/SR_LC_SL.full.bed')
('bamType', 'raw')
('refGenome', '/apps/database/hg19/ucsc.hg19.fasta')
('nCPU', 40)
('maxAltAllele', 3)
('primerDist', 2)
('bedTarget', '/apps/user/zhanglijuan/618G/UMI/smcounter2/DHS-101Z.primer3.roi.bed')
('primerSide', 1)
('mtThreshold', 0.8)
('runPath', '/apps/user/zhanglijuan/618G/UMI/smcounter2/result_M0253')
('outPrefix', 'M0253')
('ds', 10000)
('minBQ', 25)
('isRna', False)
('minMQ', 50)
('minAltUMI', 3)
rpb = 5.0, given by user
Traceback (most recent call last):
  File "/apps/user/zhanglijuan/software/smcounter2/bin/smCounter2", line 177, in <module>
    main(args)
  File "/apps/user/zhanglijuan/software/smcounter2/bin/smCounter2", line 131, in main
    for interval_result in pool.map(func,locList):
  File "/apps/user/zhanglijuan/software/Python-2.7.6/build/lib/python2.7/multiprocessing/pool.py", line 250, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/apps/user/zhanglijuan/software/Python-2.7.6/build/lib/python2.7/multiprocessing/pool.py", line 554, in get
    raise self._value
UnboundLocalError: local variable 'pos' referenced before assignment
***************************
Can you help me to solve this? Hoping to your reply. Thanks!

**Comment by lijuanzhang218** [comment]
And can you tell me how do you add UMI to bam file as such format "Mi:Z:chr1-1-115251626-CTGGGCTTGTTA      pr:Z:chr1-1-115252239-32        re:i:0  NM:i:0  AS:i:127        XS:i:0  mi:Z:CTGGGCTTGTTA"? In my own bam file added UMI, there's only has this "SA:Z:chr17,22020694,+,45S105M,3,6;      MC:Z:7H143M     MD:Z:27C50      RG:Z:41128051   NM:i:1  AS:i:73 XS:i:0  RX:Z:GGGTACGAA"

**Comment by left-castle** [comment]
Maybe it is a matter of pysam.
Which version of pysam do you use?
I had same error with pysam 0.15.4.
Now I use pysam 0.11.2.2, so it works.
